Addition of script to make tokens tradable
argentlabs/argent-contracts pull request #158
Opened 2020-09-30 07:57 UTC by juniset

Simple JS script to call the `TokenPriceRegistry` and set a list of tokens as `tradable`.

2020-10-06 10:51 UTC, elenadimitrova requested changes

2020-10-06 10:51 UTC, elenadimitrova commented on scripts/set_tradable_tokens.js
> +  // const res = await TokenPriceStorageWrapper.getTradableForTokenList(tokens);
We should check the `tradable` flag is not set on any of the submitted tokens as the contract reverts when a manager disables a tradable token.

2020-10-06 10:51 UTC, elenadimitrova commented on scripts/set_tradable_tokens.js
> +  // const res = await TokenPriceStorageWrapper.getPriceForTokenList(tokens);
We should also check there is a price set for the token we set the flag for as the contracts don't check existence of token in list before setting `tradable` flag on it meaning we can end up with tokens with 0 prices that are tradable.

2020-10-07 07:15 UTC, gergold commented
I've addressed all your comments except the last one (we can end up with tokens with 0 prices that are tradable), I'm checking with Tom and Adam what will be the process, set tradable or price first.

2020-10-07 16:43 UTC, elenadimitrova commented
Thanks @gergold can you also fix build pls `npm run lint:js` is failing

2020-10-08 15:46 UTC, elenadimitrova approved these changes

2020-10-09 10:52 UTC, merged